parameters:

    environments:

        local:
            REGION: us-west-2
            VERSION: latest
            DATABASE_PASSWORD: HIDDEN

        development:
            # If value is set to 'HIDDEN' the it will not be modified when updated
            REGION: us-west-2
            VERSION: latest
            DATABASE_PASSWORD: HIDDEN
            FUNCTION:
                function_name: deploy-lambda-php-dev
                description: ""
                memory_size: 128
                role: ""
                runtime: nodejs6.10
                timeout: 15

        production:
            # If value is set to 'HIDDEN' the it will not be modified when updated
            REGION: us-west-2
            VERSION: latest
            DATABASE_PASSWORD: HIDDEN
            FUNCTION:
                function_name: deploy-lambda-php-production
                description: ""
                memory_size: 128
                role: ""
                runtime: nodejs6.10
                timeout: 15
